### ISSUE TITLE
Cant use `useMutation` in Nextjs `React.FC`

### ISSUE THREAD

**Issue by japrozs** [FormidableLabs/urql#1706]
Hi, I had the following code inside of a project in Nextjs
```typescript
import { Form } from "formik";
import React, { useState } from "react";
import { Formik } from "formik";
import { Box, Button, WrapItemProps } from "@chakra-ui/react";
import { Wrapper } from "../components/Wrapper";
import { InputField } from "../components/InputField";
import { useMutation } from "urql";
import { ProvidedRequiredArgumentsOnDirectivesRule } from "graphql/validation/rules/ProvidedRequiredArgumentsRule";

interface RegisterProps {}

const REGISTER_MUT = `
  mutation Register($username: String!, $password: String!) {
    register(options: { username: $username, password: $password }) {
      errors {
        field
        message
      }
      user {
        id
        username
      }
    }
  }
`;

const Register: React.FC<RegisterProps> = ({}) => {
  const [, register] = useMutation(REGISTER_MUT);

  return (
    <Wrapper variant="small">
      <Formik
        initialValues={{ username: "", password: "" }}
        onSubmit={(values) => {
          register(values);
        }}
      >
        {({ isSubmitting }) => (
          <Form>
            <InputField
              name="username"
              placeholder="Username"
              label="Username"
            />
            <Box mt={4}>
              <InputField
                name="password"
                placeholder="Password"
                label="Password"
                type="password"
              />
            </Box>
            <Button
              mt={4}
              type="submit"
              colorScheme="blackAlpha"
              isLoading={isSubmitting}
              variant="solid"
            >
              Register
            </Button>
          </Form>
        )}
      </Formik>
    </Wrapper>
  );
};

export default Register;
```

I got the following error :
```bash
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/pritpalsinghsaini/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useRef (/Users/pritpalsinghsaini/node_modules/react/cjs/react.development.js:1515:20)
    at useMutation (/Users/pritpalsinghsaini/node_modules/urql/dist/urql.js:86:13)
    at Register (webpack-internal:///./src/pages/register.tsx:39:73)
    at processChild (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:211:19)
    at loadGetInitialProps (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/pritpalsinghsaini/Code/lireddit/web/node_modules/next/dist/next-server/server/render.js:54:1145)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/pritpalsinghsaini/Code/lireddit/web/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /Users/pritpalsinghsaini/Code/lireddit/web/node_modules/next/dist/next-server/server/next-server.js:105:142
```

I'm using `yarn`

**Comment by kitten** [comment]
This is likely unrelated to our hook in particular, but React's error message here is probably correct. If you run `yarn list --pattern react`, you'll see whether you have duplicate installations of `react` present.
