### ISSUE TITLE
Issue with null fields

### ISSUE THREAD

**Issue by Lowgain** [FormidableLabs/urql#21]
Hey, 

I've just started implementing this library into a project, and it's really cool so far! I've run into an issue though.

If I make a query with a null field, I receive the following error:

```
TypeError: Cannot use 'in' operator to search for '__typename' in null
    at http://localhost:4001/static/js/bundle.js:52195:24
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at http://localhost:4001/static/js/bundle.js:52199:7
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at http://localhost:4001/static/js/bundle.js:52199:7
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at http://localhost:4001/static/js/bundle.js:52199:7
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at http://localhost:4001/static/js/bundle.js:52199:7
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at http://localhost:4001/static/js/bundle.js:52199:7
    at Array.map (<anonymous>)
    at getTypeNameFromField (http://localhost:4001/static/js/bundle.js:52193:20)
    at gankTypeNamesFromResponse (http://localhost:4001/static/js/bundle.js:52186:3)
    at http://localhost:4001/static/js/bundle.js:51930:128
    at <anonymous>
```

As soon as I remove that field, everything works again. Not sure if perhaps I am missing something, but figured I should pass this along. Thanks!

**Comment by Lowgain** [comment]
Also just for a bit more information: the field is marked as nullable in my GraphQL API, and the API does successfully return a response with the field as a null value. Thanks!

**Comment by kenwheeler** [comment]
I'll get this sorted out in the morning
