### ISSUE TITLE
unable to start example, with error @babel/core

### ISSUE THREAD

**Issue by rleiwang** [FormidableLabs/urql#490]
I am trying out with the example, running int the following error. Please advise how to fix it?

```
yarn start                                                                                                                                                            master ✱
yarn run v1.12.3
$ npm run build --prefix ../../
npm WARN lifecycle The node binary used for scripts is /var/folders/jf/9rf04tc53q95b1d_76l2zv5r0000gn/T/yarn--1577237651335-0.26570406112665323/node but npm is using /usr/local/Cellar/node/12.9.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> urql@1.7.0 build /Users/workspace/urql
> rollup -c rollup.config.js

[!] Error: Cannot find module '@babel/core'
Require stack:
- /Users/workspace/urql/rollup.config.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@babel/core'
Require stack:
- /Users/workspace/urql/rollup.config.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/workspace/urql/rollup.config.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/rollup/dist/bin/rollup:832:24)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! urql@1.7.0 build: `rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the urql@1.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-12-25T01_34_11_763Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JoviDeCroock** [comment]
I think this is because you haven’t installed your root-level dependencies. Should be fixed by running yarn in urql/

**Comment by rleiwang** [comment]
@JoviDeCroock Thanks, yeah, that is it.

```
urql> yarn
urql/examples/1-getting-started> yarn
urql/examples/1-getting-started> yarn start
```
