### ISSUE TITLE
Using import in node results in not exported errors

### ISSUE THREAD

**Issue by robhicks** [FormidableLabs/urql#571]
I'm trying to use the latest version of urql in lit-element (polymer 3) app. I'm using rollup to bundle the app. The app does not need or load react. 

This is how I'm trying to configure the  urql client:
```Javascript
import { createClient, dedupExchange, cacheExchange, fetchExchange } from 'urql';
const { FS } = window || {};
const gurl = FS.appPath ? `${FS.appPath}/graphql` : 'http://localhost:5001/graphql';

const client = createClient({
  url: gurl,
  exchanges: [ dedupExchange, cacheExchange, fetchExchange ]
});

export default client;
```

The app bundle is failing to build because of this error:
```
[!] Error: 'useSubscription' is not exported by node_modules/use-subscription/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/urql/dist/urql.esm.js (5:9)
3: export * from "@urql/core";
4: 
5: import { createContext, useContext, useState, useCallback, useMemo, useEffect, useRef } from "react";
            ^
6: 
7: import { toPromise, onPush, publish, subscribe, makeSubject, map, fromValue, concat, scan, switchMap } from "wonka";
Error: 'useSubscription' is not exported by node_modules/use-subscription/index.js
    at error (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:8766:39)
    at FunctionScope.findVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at CallExpression$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at CallExpression$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:6718:15)
```

I have tried to load react (really don't want to) but still get an error:
```
!] Error: 'createContext' is not exported by node_modules/react/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/urql/dist/urql.esm.js (3:9)
1: import { createClient, createRequest } from "@urql/core";
2: 
3: export * from "@urql/core";
            ^
4: 
5: import { createContext, useContext, useState, useCallback, useMemo, useEffect, useRef } from "react";
Error: 'createContext' is not exported by node_modules/react/index.js
    at error (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:8766:39)
    at Identifier$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at CallExpression$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at CallExpression$1.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:6718:15)
    at VariableDeclarator.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at VariableDeclaration.bind (/home/robhicks/Development/idx-admin-nwc/node_modules/rollup/dist/shared/node-entry.js:3148:31)
```

**Comment by JoviDeCroock** [comment]
Hey,

If you don’t need react you should try installing and importing from @urql/core.

**Comment by robhicks** [comment]
Okay, thanks. I can try that. But it sounds like it might not be a good idea if it is going to be deprecated.

**Comment by JoviDeCroock** [comment]
`urql/core` will be deprecated `@urql/core` is the replacement. I meant you can try it out really quick just by trying that import.
The error you are getting is from a complementary `React-js` package who aren't yet using the `exports` syntax for their `package.json`

**Comment by robhicks** [comment]
ok, thanks!
