### ISSUE TITLE
@urql/exchange-graphcache: `ERR_INVALID_PACKAGE_TARGET` with Node v13.11.0

### ISSUE THREAD

**Issue by hugo** [FormidableLabs/urql#636]
[Minimal reproduction](https://github.com/hugo/urql-exchange-graphcache-node-13).

I'm afraid this is well outside the scope of my understanding so I can't offer any more useful diagnostic information at this time.

```shell
$ node index.js
Error: Invalid "exports" main target dist/urql-exchange-graphcache.esm.js defined in the package config /private/tmp/urql-exchange-graphcache-node-13/node_modules/@urql/exchange-graphcache/package.json imported from /private/tmp/urql-exchange-graphcache-node-13/index.js
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:61:13)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:191:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
```

**Comment by JoviDeCroock** [comment]
Has this ever worked for `graphql`, since they don't seem to have correct export maps either https://github.com/graphql/graphql-js/blob/master/package.json

**Comment by hugo** [comment]
```js
import * as graphql from 'graphql'

console.log(graphql)
```

```
$ node index.js 
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/tmp/urql-exchange-graphcache-node-13/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

I don't know that this is a _huge_ issue *right now* since it's not a bug in an LTS release, but Node 14 is coming in April.

**Comment by JoviDeCroock** [comment]
Yes, I think the ecosystem isn't prepared for it yet. We've put up PR's to prepare but if peerDeps aren't prepared we will have difficulties

**Comment by kitten** [comment]
Welp! It’s working correctly, but Bundlephobia doesn’t like it due to a Webpack config quirk. PR opened and I hope this won’t be an issue for anyone else
