### ISSUE TITLE
[next-urql] Next-Urql appears to be broken

### ISSUE THREAD

**Issue by JoeHart** [FormidableLabs/urql#883]
👋 Hey gang! Was just trying to get `next-urql` working in my next.js app, I kept getting:

```
Error: ReactDOMServer does not yet support Suspense.
    at ReactDOMServerRenderer.read (/Users/joehart/workspace/pride-flag-api/node_modules/react-dom/cjs/react-dom-server.node.development.js:3387:25)
    at renderToString (/Users/joehart/workspace/pride-flag-api/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/render.js:3:298)
    at Object.renderPage (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/render.js:46:1020)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:133:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:20:85)
    at loadGetInitialProps (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/render.js:46:1330)
    at async /Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:68:285
    at async /Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:67:142
    at async DevServer.renderToHTMLWithComponents (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:91:254)
    at async DevServer.renderToHTML (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:92:254)
    at async DevServer.renderToHTML (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/server/next-dev-server.js:22:539)
    at async DevServer.render (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:48:236)
    at async Object.fn (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/joehart/workspace/pride-flag-api/node_modules/next/dist/next-server/server/router.js:28:28)
```

I thought this might be to do with my set up but this error is also present in the `next-urql` codesandbox here: https://codesandbox.io/s/next-urql-pokedex-oqj3x

As seen:

![Screenshot 2020-06-28 at 22 22 22](https://user-images.githubusercontent.com/1856468/85958507-df884b00-b98d-11ea-94c5-430cb44c968a.png)

urql version & exchanges: 1.9.8

**Steps to reproduce**

1. Go to: https://codesandbox.io/s/next-urql-pokedex-oqj3x

**Expected behavior**

The example should render the pokemon in SSR

**Actual behavior**

Throws a `ReactDOMServer does not yet support Suspense.` error.

**Comment by JoeHart** [comment]
I am going to attempt to go digging to figure this out, but have never touched the Urql codebase before so thought I'd raise here incase it's an obvious fix 😄

**Comment by JoviDeCroock** [comment]
Hey @JoeHart 

So the issue has a bit of a nuance to it, you have found a bug where we didn't bind `getInitialProps` to the `withUrqlClient` this mean that `react-ssr-prepass` doesn't run which enables suspense on the server.

If you have children of this page that do need to have a prepass run you should considere using the [`ssr option` (see last part)](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs) of next-urql to enable this.

If you don't have any `getInitialProps` runs then the linked PR should resolve your issue.

**Comment by JoeHart** [comment]
Ah amazing thank you! 😄 Yea it was just an extremely simple only one `useQuery` inside the page render method which then passes data down to components with no data fetching any deeper than that.
