### ISSUE TITLE
`changeset` no longer works since `master` changed to `main`

### ISSUE THREAD

**Issue by dotansimha** [FormidableLabs/urql#905]
I was working on this PR: https://github.com/FormidableLabs/urql/pull/904 and noticed that I can't use `changeset` command now. 

```
➜  urql: yarn changeset
yarn run v1.22.4
$ /Users/dotansimha/Dev/urql/node_modules/.bin/changeset
🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?
🦋  error     at getDivergedCommit (/Users/dotansimha/Dev/urql/node_modules/@changesets/git/dist/git.cjs.dev.js:51:11)
🦋  error     at async getChangedFilesSince (/Users/dotansimha/Dev/urql/node_modules/@changesets/git/dist/git.cjs.dev.js:69:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/Users/dotansimha/Dev/urql/node_modules/@changesets/git/dist/git.cjs.dev.js:108:24)
🦋  error     at async add (/Users/dotansimha/Dev/urql/node_modules/@changesets/cli/dist/cli.cjs.dev.js:369:29)
🦋  error     at async /Users/dotansimha/Dev/urql/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1008:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JoviDeCroock** [comment]
Hey,

I fixed it, this should be okay now when rebased with `main`.

**Comment by dotansimha** [comment]
It works now, thanks @JoviDeCroock

**Comment by danielcnascimento** [comment]
any workaround?
