### ISSUE TITLE
Next-Urql problem on Vercel

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#931]
When deploying the newest version of next-urql and urql (1.10) it crashes my application with the following error:

```Bash
[GET] /
23:04:12:39
2-4dc2-9081-3efa23019e0f	ERROR	Unhandled error during request: SyntaxError: Unexpected token d in JSON at position 0    at JSON.parse (<anonymous>)    at module.exports.cha2.__webpack_exports__.default.Object.ssr (/var/task/.next/serverless/pages/index.js:2998:122)    at Function._ref4 [as getInitialProps] (/var/task/node_modules/next-urql/dist/next-urql.js:117:32)    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:22:1221)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async renderReqToHTML (/var/task/.next/serverless/pages/index.js:1495:22)    at async Server.render (/var/task/.next/serverless/pages/index.js:1568:22)2020-08-02T23:04:12.452Z	660f4ab6-4ed2-4dc2-9081-3efa23019e0f	ERROR	Failed call /_error subroutine, continuing to crash function: SyntaxError: Unexpected token d in JSON at position 0    at JSON.parse (<anonymous>)    at module.exports.cha2.__webpack_exports__.default.Object.ssr (/var/task/.next/serverless/pages/index.js:2998:122)    at Function._ref4 [as getInitialProps] (/var/task/node_modules/next-urql/dist/next-urql.js:117:32)    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:22:1221)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async renderReqToHTML (/var/task/.next/serverless/pages/index.js:1530:13)    at async Server.render (/var/task/.next/serverless/pages/index.js:1568:22)2020-08-02T23:04:12.453Z	660f4ab6-4ed2-4dc2-9081-3efa23019e0f	ERROR	SyntaxError: Unexpected token d in JSON at position 0    at JSON.parse (<anonymous>)    at module.exports.cha2.__webpack_exports__.default.Object.ssr (/var/task/.next/serverless/pages/index.js:2998:122)    at Function._ref4 [as getInitialProps] (/var/task/node_modules/next-urql/dist/next-urql.js:117:32)    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:22:1221)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async renderReqToHTML (/var/task/.next/serverless/pages/index.js:1495:22)    at async Server.render (/var/task/.next/serverless/pages/index.js:1568:22)2020-08-02T23:04:12.453Z	660f4ab6-4ed2-4dc2-9081-3efa23019e0f	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"SyntaxError: Unexpected token d in JSON at position 0","reason":{"errorType":"SyntaxError","errorMessage":"Unexpected token d in JSON at position 0","stack":["SyntaxError: Unexpected token d in JSON at position 0","    at JSON.parse (<anonymous>)","    at module.exports.cha2.__webpack_exports__.default.Object.ssr (/var/task/.next/serverless/pages/index.js:2998:122)","    at Function._ref4 [as getInitialProps] (/var/task/node_modules/next-urql/dist/next-urql.js:117:32)","    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)","    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:22:1221)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async renderReqToHTML (/var/task/.next/serverless/pages/index.js:1495:22)","    at async Server.render (/var/task/.next/serverless/pages/index.js:1568:22)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: SyntaxError: Unexpected token d in JSON at position 0","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}Unknown application error occurred
```
(Sorry for the bad formatting, not sure how to fix it)

I already removed the `node_modules` and the `yarn.lock` and reinstalled. It didnt fix the issue.
It works fine on my local pc though

Edit: I tried downgrading to `urql: 1.9.8`, `next-urql: 1.0.2` and `@urql/exchange-graphcache: 3.0.1`, but in my `yarn.lock` 

I still have:
```
"@urql/core@>=1.12.0", "@urql/core@>=1.12.1", "@urql/core@^1.12.0", "@urql/core@^1.12.3":
  version "1.12.3"
  resolved "https://registry.yarnpkg.com/@urql/core/-/core-1.12.3.tgz#74f7b8e073cf706380bb3dd28484b8136cc96905"
  integrity sha512-e4IXXQ4nes3KyusgYV925DuzfDAfo4ex7Ls3tZfOExkxEcXh0i0XnizXp0rvZmWRch69YCkc+Lh1Gy2aY49HTQ==
  dependencies:
    wonka "^4.0.14"
```
so the newest `@urql/core` version.

**Comment by kitten** [comment]
That doesn't really sound like a problem with `urql` or `next-urql`, since the underlying error is:

> SyntaxError: Unexpected token d in JSON at position 0

What makes you think it may not be the API? 🤔

**Comment by BjoernRave** [comment]
@kitten you are right, was sth else. Next time I will look more closely before opening an issue...

**Comment by kitten** [comment]
@BjoernRave No worries! Glad I could help!
