### ISSUE TITLE
Codesandbox demo is not working

### ISSUE THREAD

**Issue by AmazingTurtle** [FormidableLabs/urql#99]
https://codesandbox.io/s/p5n69p23x0.

Response

```
{
  "code": 400,
  "error": "Script returned an error.",
  "details": "Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.",
  "name": "Error",
  "message": "Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.",
  "stack": "Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.\n    at invariant (/data/_verquire/graphql/0.11.7/node_modules/graphql/jsutils/invariant.js:18:11)\n    at validate (/data/_verquire/graphql/0.11.7/node_modules/graphql/validation/validate.js:59:72)\n    at /data/_verquire/graphql/0.11.7/node_modules/graphql/graphql.js:69:51\n    at new Promise (<anonymous>)\n    at graphqlImpl (/data/_verquire/graphql/0.11.7/node_modules/graphql/graphql.js:59:10)\n    at Object.graphql (/data/_verquire/graphql/0.11.7/node_modules/graphql/graphql.js:48:227)\n    at /data/io/bd8d6406-646c-4a14-8377-1a244f3dba80/webtask.js:140:26\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
}
```

**Comment by kitten** [comment]
Duplicate of https://github.com/FormidableLabs/urql/issues/80
